apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-zano-pool-api-deployment
  labels:
    app: open-zano-pool-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-zano-pool-api
  template:
    metadata:
      name: open-zano-pool-api
      labels:
        app: open-zano-pool-api
    spec:
      volumes:
      - name: config
        secret:
          secretName: api-config-file
      containers:
      - name: oovp-test-container
        image: lgray/open-zano-pool-api:latest
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        args: ['/config/config.api.json'] 
        ports:
        - containerPort: 21111 # polling api
        imagePullPolicy: Always