apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-zano-pool-frontend-deployment
  labels:
    app: open-zano-pool-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-zano-pool-frontend
  template:
    metadata:
      name: open-zano-pool-frontend
      labels:
        app: open-zano-pool-frontend
    spec:
      containers:
      - name: oovp-test-container
        image: lgray/open-zano-pool-frontend:latest
        env:
        - name: TZ
          value: "Etc/Universal"
        args: ['server', '--host', '0.0.0.0', '--port', '80', '-dev']
        ports:
        - containerPort: 80 # http
        - containerPort: 7020 # live reload
        imagePullPolicy: Always
