apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-zano-pool-payouts-deployment
  labels:
    app: open-zano-pool-payouts
spec:
  replicas: 1 # ONLY EVER ONE OF THESE!!!
  selector:
    matchLabels:
      app: open-zano-pool-payouts
  template:
    metadata:
      name: open-zano-pool-payouts
      labels:
        app: open-zano-pool-payouts
    spec:
      volumes:
      - name: config
        secret:
          secretName: payouts-config-file  
      containers:
      - name: oovp-test-container
        image: lgray/open-zano-pool-api:latest
        env:
        - name: POOL_MINER_KEY
          valueFrom:
            secretKeyRef:
              name: pool-miner-key
              key: value 
        - name: POOL_MINER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: pool-miner-private-key
              key: value
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        args: ['/config/config.payouts.json']
        imagePullPolicy: Always