apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-zano-pool-proxy-deployment
  labels:
    app: open-zano-pool-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-zano-pool-proxy
  template:
    metadata:
      name: open-zano-pool-proxy
      labels:
        app: open-zano-pool-proxy
    spec:
      volumes:
      - name: config
        secret:
          secretName: proxy-config-file
      containers:
      - name: oovp-test-container
        image: lgray/open-zano-pool-api:latest
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        args: ['/config/config.proxy.json']
        ports:
        - containerPort: 12111 # stratum mining
        - containerPort: 11112 # http mining
        imagePullPolicy: Always
