apiVersion: v1
kind: Service
metadata:
  name: open-zano-pool-frontend
spec:
  ports:
  - name: web
    port: 80
  - name: livereload
    port: 7020
  selector:
    app: open-zano-pool-frontend
  externalIPs:
  - 157.245.116.220
---
apiVersion: v1
kind: Service
metadata:
  name: open-zano-pool-api
spec:
  ports:
  - name: api
    port: 21111
  selector:
    app: open-zano-pool-api
  externalIPs:
  - 157.245.116.220
---
apiVersion: v1
kind: Service
metadata:
  name: open-zano-pool-proxy
spec:
  ports:
  - name: stratum-mining
    port: 12111
  - name: http-mining
    port: 11112
  selector:
    app: open-zano-pool-proxy
  externalIPs:
  - 157.245.116.220
