apiVersion: v1
kind: Service
metadata:
  name: open-zano-pool-frontend
spec:
  ports:
  - name: web
    port: 80
  - name: livereload
    port: 7020
  selector:
    app: open-zano-pool-frontend
  externalIPs:
  - 143.110.217.248
---
apiVersion: v1
kind: Service
metadata:
  name: open-zano-pool-api
spec:
  ports:
  - name: api
    port: 21111
  selector:
    app: open-zano-pool-api
  externalIPs:
  - 143.110.217.248
