apiVersion: apps/v1
kind: Deployment
metadata:
  name: zano-deployment
  labels:
    app: zano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zano
  template:
    # template for bcnode pods
    metadata:
      labels:
        app: zano
    spec:
      volumes:
      - name: vol-zano-db
        persistentVolumeClaim:
          claimName: pvc-zano-db
      - name: wallet
        secret:
          secretName: pool-wallet-file
      containers:
      - name: zano
        stdin: true
        tty: true
        image: lgray/zano-testnet:latest
        volumeMounts:
        - mountPath: /home/zano/.Zano
          name: vol-zano-db
        env:
        - name: POOL_MINER_KEY
          valueFrom:
            secretKeyRef:
              name: pool-miner-key
              key: value
        ports:
        - name: rpc
          protocol: TCP
          containerPort: 11211
        - name: bcbootstrap
          protocol: TCP
          containerPort: 11200
        imagePullPolicy: Always
      - name: zano-wallet
        stdin: true
        tty: true
        image: lgray/zano-testnet:latest
        volumeMounts:
        - mountPath: /home/zano/.Zano
          name: vol-zano-db
        - name: wallet
          mountPath: "/wallet"
        env:
        - name: POOL_MINER_PWD
          valueFrom:
            secretKeyRef:
              name: pool-miner-pwd
              key: value
        command: [./simplewallet]
        args: ["--wallet-file","/wallet/pool_dummy.keys","--password","$(POOL_MINER_PWD)","--rpc-bind-ip","0.0.0.0","--rpc-bind-port","11212","--daemon-port","11211"]
        ports:
        - name: wallet-rpc
          protocol: TCP
          containerPort: 11212
        imagePullPolicy: Always