kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol-zano-db
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/vol-zano-db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-zano-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: vol-zano-db
  resources:
    requests:
      storage: 20Gi
