apiVersion: v1
kind: Service
metadata:
  name: zano-svc
spec:
  selector:
    app: zano
  ports:
  - name: rpc
    protocol: TCP
    port: 11211
    targetPort: 11211
  - name: wallet-rpc
    protocol: TCP
    port: 11212
    targetPort: 11212
---
apiVersion: v1
kind: Service
metadata:
  name: zano-svc-external
spec:
  selector:
    app: zano
  ports:
  - name: zano
    protocol: TCP
    port: 11121
    targetPort: 11121
  - name: stratum-mining
    port: 12111
  - name: http-mining
    port: 11112
  externalIPs:
  - 143.110.217.248